---
site_name: Transformaci칩n tecnol칩gica de la empresa Inmosolutions
site_description: Dise침ar e implementar una unidad de DevOps
site_author: Grupo3
repo_name: UAX-BigData-Grupo3/inmosolutions

repo_url: https://github.com/UAX-BigData-Grupo3/inmosolutions
nav:
  - Inicio: "01_index.md"
  - Modelo actual: "02_modelo_actual.md"
  - Retos planteados: "03_retos_planteados.md"
  - Objetivos de futuro: "04_objetivos_futuro.md"
  - Soluci칩n propuesta: "05_solucion_propuesta.md"
plugins:
  - search:
      lang: es
theme:
  name: material
  logo: assets/uax.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: indigo
  font:
    text: Roboto
  features:
    - navigation.tabs
    - header.autohide
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  language: es

copyright: Copyright &copy; 2022 - 2023 | Grupo3
