---
site_name: Transformación tecnológica de la empresa Inmosolutions
site_description: Diseñar e implementar la unidad de DevOps
de una organización siguiendo los lineamientos establecidos
en el modelo SRE. Se debe contemplar la
implementación desde el punto de vista organizacional
hasta la especificación del stack tecnológico a desarrollar.
site_author: Grupo3
repo_name: UAX-BigData-Grupo3/inmosolutions

repo_url: https://github.com/UAX-BigData-Grupo3/inmosolutions
nav:
  - Inicio: "index.md"
  - Modelo actual: "modelo.md"
  - Modelo futuro: "tecnologias.md"
  - Propuesta de solución: "solucion.md"
plugins:
  - search:
      lang: es
theme:
  name: material
  logo: assets/uax.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: indigo

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: indigo
  font:
    text: Roboto
  features:
    - navigation.tabs
    - header.autohide
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
  language: es

copyright: Copyright &copy; 2022 - 2023 | Grupo3
